name: Java CI with Maven and PostgreSQL

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-and-test:
    runs-on: ubuntu-slim

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_DB: attendance_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test999
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test with Maven
        run: mvn clean verify -Dspring.profiles.active=integration
